CSHARP/OENIK_PROG3_2019_2_JHZF2T/IssueTracker.WebApp/Models/ProjectsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Net.Easimer.Prog3.IssueTracker.WebApp.Models
{
    public class ProjectsViewModel
    {
        public IEnumerable<ProjectModel> Projects { get; set; }
        public ProjectModel Edited { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_JHZF2T/IssueTracker.WebApp/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Net.Easimer.Prog3.Database;
using Net.Easimer.Prog3.IssueTracker.WebApp.Models;

namespace Net.Easimer.Prog3.IssueTracker.WebApp.Controllers
{
    public class ProjectsController : Controller
    {
        private IIssueTracker issueTracker;
        private IProjectManagement projMgmt;
        private IUserManagement userMgmt;
        private IMapper mapper;
        private ProjectsViewModel vm;

        public ProjectsController()
        {
            IDataAccess datacc = new DataAccessImpl();
            issueTracker = new IssueTracker(datacc);
            projMgmt = issueTracker.GetProjectManagement();
            userMgmt = issueTracker.GetUserManagement();

            mapper = MapperFactory.CreateMapper();

            vm = new ProjectsViewModel();
            vm.Edited = new ProjectModel();
            vm.Projects = projMgmt.GetAllProjects().Select(p => mapper.Map<ProjectInfo, ProjectModel>(p)).ToList();
        }

        private ProjectModel GetById(int id)
        {
            return mapper.Map<ProjectInfo, ProjectModel>(projMgmt.GetByID(id));
        }

        // GET: Projects
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            ViewData["editResult"] = string.Empty;
            return View("ProjectIndex", vm);
        }

        public ActionResult Details(int id)
        {
            return View("ProjectDetails", GetById(id));
        }

        public ActionResult Delete(int id)
        {
            var res = projMgmt.DeleteByID(id);
            TempData["editResult"] = res ? "Delete OK" : "Delete fail";
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.Edited = GetById(id);
            return View("ProjectIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(ProjectModel proj, string editAction)
        {
            if(ModelState.IsValid && proj != null)
            {
                bool res = false;
                switch(editAction)
                {
                    case "AddNew":
                        res = projMgmt.CreateProject(proj.Id, proj.Name, proj.Homepage, null) != null;
                        break;
                    case "Edit":
                        var oldProj  = projMgmt.GetByID(proj.Id);
                        oldProj.Name = proj.Name;
                        oldProj.Homepage = proj.Homepage;
                        oldProj.Owner = proj.Owner;
                        projMgmt.Modify(proj.Id, oldProj);
                        res = true;
                        break;
                }

                ViewData["editResult"] = res ? "Edit OK" : "Edit fail";

                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.Edited = proj;
                return View("ProjectIndex", vm);
            }
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_JHZF2T/IssueTracker.WebApp/Views/Projects/ProjectDetails.cshtml
@using Net.Easimer.Prog3.IssueTracker.WebApp.Models
@model ProjectModel 
@{
    ViewBag.Title = "ProjectDetails";
}

<h2>Project details</h2>

@Html.ActionLink("Back to the listing", "Index")

<table class="table">
    <tr><th scope="row">@Html.DisplayNameFor(m => m.Id)</th><td>@Html.DisplayFor(m => m.Id)</td></tr>
    <tr><th scope="row">@Html.DisplayNameFor(m => m.Name)</th><td>@Html.DisplayFor(m => m.Name)</td></tr>
    <tr><th scope="row">@Html.DisplayNameFor(m => m.Owner)</th><td>@Html.DisplayFor(m => m.Owner)</td></tr>
    <tr><th scope="row">@Html.DisplayNameFor(m => m.OwnerName)</th><td>@Html.DisplayFor(m => m.OwnerName)</td></tr>
    <tr><th scope="row">@Html.DisplayNameFor(m => m.Homepage)</th><td>@Html.DisplayFor(m => m.Homepage)</td></tr>
    <tr><th scope="row">@Html.DisplayNameFor(m => m.CreationDate)</th><td>@Html.DisplayFor(m => m.CreationDate)</td></tr>
    <tr><th scope="row">@Html.DisplayNameFor(m => m.Parent)</th><td>@Html.DisplayFor(m => m.Parent)</td></tr>
    <tr><th scope="row">@Html.DisplayNameFor(m => m.ParentProjectName)</th><td>@Html.DisplayFor(m => m.ParentProjectName)</td></tr>
</table>

CSHARP/OENIK_PROG3_2019_2_JHZF2T/IssueTracker.WebApp/Views/Projects/ProjectEditView.cshtml
@model Net.Easimer.Prog3.IssueTracker.WebApp.Models.ProjectModel

<h2>Project editor</h2>

@using (Html.BeginForm("Edit", "Projects"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.OwnerName)
    @Html.HiddenFor(m => m.ParentProjectName)
    @Html.HiddenFor(m => m.Parent)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Homepage)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Homepage)</div>

    <div class="editor-label">@Html.LabelFor(m => m.CreationDate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.CreationDate)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Owner)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Owner)</div>

    <input type="submit" />
}

CSHARP/OENIK_PROG3_2019_2_JHZF2T/IssueTracker.WebApp/Views/Projects/ProjectIndex.cshtml
@model Net.Easimer.Prog3.IssueTracker.WebApp.Models.ProjectsViewModel
@{
    ViewBag.Title = "ProjectIndex";
}

<h2>Projects index</h2>
<p>@TempData["editResult"]</p>

@Html.Partial("ProjectEditView", Model.Edited)
@Html.Partial("ProjectListView", Model.Projects)

CSHARP/OENIK_PROG3_2019_2_JHZF2T/IssueTracker.WebApp/Views/Projects/ProjectListView.cshtml
@model IEnumerable<Net.Easimer.Prog3.IssueTracker.WebApp.Models.ProjectModel>

<h2>List of projects</h2>

@if(Model.Count() == 0)
{
    <h3>The list is empty!</h3>
}
else
{
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Owner)</th>
            <th>@Html.DisplayNameFor(m => m.First().Homepage)</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        @foreach(var proj in Model)
        {
            <tr>
                <td>@Html.DisplayFor(_ => proj.Name)</td>
                <td>@Html.DisplayFor(_ => proj.OwnerName)</td>
                <td><a href="@Html.DisplayFor(_ => proj.Homepage)">@Html.DisplayFor(_ => proj.Homepage)</a></td>
                <td>@Html.ActionLink("Details", "Details", new { id = proj.Id })</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = proj.Id })</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id = proj.Id })</td>
            </tr>
        }
    </table>
}